### ISSUE TITLE
Enrichir les données de démo

### ISSUE THREAD

**Issue by alaumiere** [twigy/twigy-backend#1]
Avec le passage de Parse à une base locale mongo, il faudrait récupérer les données qu'il y avait sur Parse pour les intégrer dans nos scripts d'init (sous /app/db).
L'objectif est de peupler la base lorsqu'elle est vide avec des données minimales pour une démo.
Actuellement, seul l'utilisateur **a** est présent.

**Comment by robbee** [comment]
Yo ! J'ai poussé des users dans le script .. et placé des photos dans app/people 

Dis moi si ça te convient (pas réussi a crypter le pwd...)

**Comment by alaumiere** [comment]
merci, on va bientôt pouvoir se passer de Parse. \o/
N'hésite pas à ajouter/vérifier les models, le backend c'est pas mon fort ;-)

**Comment by robbee** [comment]
Wahoo 😍

Le mardi 22 mars 2016, alaumiere <notifications@github.com> a écrit :

> merci, on va bientôt pouvoir se passer de Parse. \o/
> N'hésite pas à ajouter/vérifier les models, le backend c'est pas mon fort
> ;-)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/twigy/twigy-backend/issues/1#issuecomment-199861453>
>


--
